### ISSUE TITLE
PHP 5.6 and certificates problem

### ISSUE THREAD

**Issue by beherit** [samuelaguilera/sar-friendly-smtp#1]
Please add to plugin option to disable certificate verification because is a problem with sending mails in PHP 5.6 - example:

```
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```

More info: https://www.portalzine.de/dev/wp/php-5-6-phpmailer-wordpress-connection-errors/

**Comment by samuelaguilera** [comment]
This is not a problem or issue caused by the plugin but by a misconfiguration in some servers. And you already have the solution in that post, that is applied to PHPMailer directly so it will fix the issue with any plugin that you may be using.

Thanks for the suggestion but I'm not going to add this to the plugin.

**Comment by beherit** [comment]
But the solution need changes in Your plugin, I can't add this in other plugin :/

**Comment by beherit** [comment]
Ok, my bad - I wrote plugin that should fix it.
