### ISSUE TITLE
Getting error, no log created, plugin seems to not work?

### ISSUE THREAD

**Issue by TrishaM** [samuelaguilera/sar-friendly-smtp#11]
Greetings Samuel,

First, kudos on a lovely and simple plugin.  However I’m having issues and not sure what to try next as I cannot find the PHP error_log file even though I've searched all over the server (root, root folder of website, logs folder, etc). 

When I activate the plugin and enter all the settings, including a FROM name/address, I get this error message on the 'send test email' page:

> WordPress was not able to pass the email to the SMTP server.
> 
> Error returned by PHPMailer class: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Unfortunately I don't understand what the page wants me to do.

I've verified that the settings are correct per my email host company - they gave me the host, port, and encryption info which I've very carefully entered so I'm sure of no typos. 

I'm using WP version 4.4.2 (not able to upgrade until August) and the version of your plugin is 1.2.3 - is there something else I can do?   I enabled debugging but as mentioned I can't find the error_log file even though I have S/FTP access and have searched all over the server. 

Any suggestions would be most appreciated!

**Comment by samuelaguilera** [comment]
Hi @TrishaM,

That error is literally indicating you that WP was not able to connect to the SMTP server with the details that you have configured. This is usually caused by incorrect settings (most of the time wrong host address or port).

If you're 100% sure the details configured are the correct ones, you will want to contact with your host support for further investigation of the issue, only the server admin can help in this situation. And the same for error logs, your host support should be able to locate the logs, check what happened and fix it.

In any case this is an issue between your web server and the SMTP server configured, unfortunately there's nothing I can do from the plugin side of things.

If the host is not willing to help, I would recommend you to try a transactional email provider, all of them have SMTP servers and almost all offer a free account with large number of emails sent per month to let you try their services. You can see a great list of providers here: https://www.metachris.com/2016/03/free-transactional-email-services-the-best-alternatives-to-mandrill/

**Comment by TrishaM** [comment]
Hi Samuel,

Many thanks for the prompt response!

We use zMailcloud as our email hosting provider, which is different from the website hosting company, and they (zMailcloud) gave me the settings I used……..so I’ll get in touch with both of them to see if they can help me diagnose this further.

Best regards,
Trisha
