### ISSUE TITLE
PHP Mailer fatal error since WP 4.6

### ISSUE THREAD

**Issue by BoweFrankema** [samuelaguilera/sar-friendly-smtp#4]
Hi Samuel,

Thank you for a great plugin, it's been critical to our clients who use BuddyPress heavily and need HTML emails AND SMTP. Your plugin has been the only solution that works for them.

Sadly since WordPress 4.6 we're running into fatal errors when emails are being sent out.. 

`Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /usr/src/wordpress/wp-includes/class-phpmailer.php:946 Stack trace: #0 /usr/src/wordpress/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress', false) #1 /usr/src/wordpress/wp-content/plugins/s2member/includes/classes/email-configs.inc.php(432): wp_mail('support@seniorc...', '[Senior Chatter...', 'New User Regist...', 'Content-Type: t...') #2 [internal function]: c_ws_plugin__s2member_email_configs::new_user_notification(33245, 'Brasco2207', Array) #3 /usr/src/wordpress/wp-content/plugins/s2member/includes/functions/pluggables.inc.php(81): call_user_func_array('c_ws_plugin__s2...', Array) #4 /usr/src/wordpress/wp-content/plugins/s2member-pro/includes/classes/gateways/paypal/paypal-registration-in.inc.php(116): wp_new_user_notification(33245, NULL, 'admin', 'Brasco2207') #5 /usr/src/wordpress/wp-content/plugins/s2member-pro/includes/classes/gateways/paypal/paypal-registration.inc.php(60): c_ws_plugin__ in /usr/src/wordpress/wp-includes/class-phpmailer.php on line 946`

In this case it happens via a S2Member email, but it happens with others as well.. The solution I've implemented can be found here: https://github.com/Automattic/vip-quickstart/issues/512#issue-165799484.

But maybe there is a way to add this to your plugin?

**Comment by samuelaguilera** [comment]
Hi Bowe!

Thanks for your comments. Looking at the link provided and the [ticket in core trac](https://core.trac.wordpress.org/ticket/25239) I can see that the issue is due to the way WordPress core  obtain the domain for the email address in certain server setups.

This plugin is not involved in that process so I'm afraid that will need to be solved by WP core team (for emails sent by core) or the plugin that is creating the email (S2Member in your case).
